Feature/GPP-4: Submission Form Metadata Entry
CityOfNewYork/DORIS-Publications-Portal pull request #25
Opened 2017-05-31 22:46 UTC by gzhou1

2017-06-13 14:21 UTC, joelbcastillo requested changes

2017-06-13 14:21 UTC, joelbcastillo commented on app/main/views.py
> +    from app.database.user import get_first, create
What is the reasoning behind importing within the function? Is this function just for testing?

If so, please add a comment describing it's purpose and a `TODO` to remove this before deploying to a live environment. Might be best to put any testing functionality behind a check for `current_app.config['TESTING']`

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/lib/schema_utils.py
> +    '''Validate 'required' properties.'''
Can you update the docstring to follow this standard:

```python
"""
One line docstring in the imperative.

:param param_1: Description of param
...

:returns: Return value
"""
```

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/lib/schema_utils.py
> +def validate_json(data, schema_path, schema_name):
See note above RE: docstrings.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +# from app.models import Document
Is there a reason this was left here?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +        except Exception as e:
I think as a rule we should start catching specific exceptions. This may be here because we haven't done much on the backend API *yet*, but it is something we should keep in mind.

Also, I think part of our exception catching should be logging. For now we should setup logging to a file for errors like these. It should help with debugging. Eventually we need to setup a log capture utility so that we can view the alerts outside of the server the app is running on.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +            for file_ in json["files"]:
Can we split up some of the more detailed logic (such as specific file checking) into utils or private methods? I still think business logic should be as separate as possible from the API itself. Let me know what you think.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +            # TODO: offset by timezone
Can we pull the same functions from OpenRecords?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +            doc = Document(1,  # id
If we aren't using a custom formatted `id`, can this be left blank?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +    def post(self):
See notes about docstrings.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/report_types/api.py
> +                ReportType("Adjunctions / Decisions", "adjunctions_decisions"),
This will be stored in the database, right? I don't think it makes sense to have this hardcoded into the application.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/report_types/api.py
> +    def get(self):
Do we need a separate endpoint to get a single `ReportType`?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/subjects/api.py
> +    def get(self):
Do we need an endpoint for a single subject?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/subjects/api.py
> +                Subject("Accounting", "accounting"),
Database? Or a constants file?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +        :param dirname: name of directory within the uploads directory in which to save the uploaded file
What does this `return`?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +            # upload_path = /uploads/123/file.pdf
These comments for test code? Or are they meant to be explanatory?

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +            return api_response.fail("This is not a PDF file. Please remove.")
I think we need to run our error messages through the business owner just to make sure they are ok. 

Also, should we setup a constants file for the error messages? I think it makes things clearer (if we choose our constant names correctly) and makes it a lot easier to change things if needed.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +        :param filename: name of previously uploaded file
Missing your `return` documentation.

2017-06-13 14:21 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +        is_pdf = magic.from_buffer(file_.read(1024), mime=True) == "application/pdf"
#TODO: We need to include virus scanning here.

2017-06-13 14:21 UTC, joelbcastillo commented on app/schemas/v1/document/report_type.json
> +    "report_type": {
Can we pull the values for the reports / subjects from the json files instead of hardcoding them?

This only applies if we aren't going to store these in the database separately. If we do store them in the database, we may need to figure out a way (probably dynamically fill in the valid values) to validate against the schema, since it will not be (may not be?) up to date on the filesystem.

2017-06-13 14:21 UTC, joelbcastillo commented on app/schemas/v1/document/subjects.json
> +    "subjects": {
See note regarding the storage of report type schema.

2017-06-13 14:21 UTC, joelbcastillo commented on app/schemas/v1/document/submission.json
> +                "maxLength": "Please shorten your description to at most 200 characters.",
Did we run the error messages through with the business owner?

2017-06-13 14:21 UTC, joelbcastillo commented on app/templates/index.html
> +<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scal
Is this auto-generated by npm? Or is there another reason the spacing is missing?

2017-06-13 14:21 UTC, joelbcastillo commented on gpp/src/components/DateInput.js
> +    // update the date value if the format is valid, even though the date itself might be wrong
Date validation happens on backend then?

2017-06-13 14:21 UTC, joelbcastillo commented on gpp/src/components/FileUpload.js
> +      errorMsg = "Failed to upload file due to an unhandled server error."
Let's run these error messages through the business owner.

2017-06-20 16:04 UTC, zgary commented on app/resources/v1/document/api.py
> +# from app.models import Document
Removed. Not currently used in this feature.

2017-06-20 16:04 UTC, zgary commented on app/main/views.py
> +    from app.database.user import get_first, create
Added comment indicating that this is for testing purposes.

2017-06-20 16:04 UTC, zgary commented on gpp/src/components/DateInput.js
> +    // update the date value if the format is valid, even though the date itself might be wrong
Yes.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/document/api.py
> +        except Exception as e:
I've looked online and many of the use cases of `get_json` do not have a try block. In the few cases that I've seen, only the general Exception is caught. I've tried to play around with it and I've gotten AttributeError raised but there might be more specific exceptions that I don't know about.

I agree that we should setup logging early on to help with debugging.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/document/api.py
> +            # TODO: offset by timezone
Yes we can.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/document/api.py
> +            doc = Document(1,  # id
We are currently not committing to the db so a custom formatted `id` is used for testing. This will be left blank when we write to the db.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/report_types/api.py
> +    def get(self):
I can't think of a case where we would need to.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/subjects/api.py
> +    def get(self):
I can't think of a case where we would need to.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/subjects/api.py
> +                Subject("Accounting", "accounting"),
Database. Added a To-Do.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/upload/api.py
> +            # upload_path = /uploads/123/file.pdf
Removed. They were for test code.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/upload/api.py
> +            return api_response.fail("This is not a PDF file. Please remove.")
I agree that we should run our error messages through the business owner.

The only argument I have for not putting the error messages in a constant file is that this message is only in this one place. If you think that setting up a constants file would be more preferable, I would be okay with that too.

2017-06-20 16:04 UTC, gzhou1 commented on app/resources/v1/upload/api.py
> +        is_pdf = magic.from_buffer(file_.read(1024), mime=True) == "application/pdf"
Added TODO.

2017-06-20 16:04 UTC, gzhou1 commented on app/schemas/v1/document/report_type.json
> +    "report_type": {
The plan is to store the report_type and subjets in the database. We will need to figure out a way to dynamically populate the values.

2017-06-20 16:04 UTC, gzhou1 commented on app/schemas/v1/document/subjects.json
> +    "subjects": {
Acknowledged.

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/lib/schema_utils.py
> +def validate_json(data, schema_path, schema_name):
👍

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +    def post(self):
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +            for file_ in json["files"]:
So we decided not to do this for now?

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/document/api.py
> +            doc = Document(1,  # id
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/report_types/api.py
> +    def get(self):
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/subjects/api.py
> +    def get(self):
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +        :param dirname: name of directory within the uploads directory in which to save the uploaded file
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +            return api_response.fail("This is not a PDF file. Please remove.")
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/resources/v1/upload/api.py
> +        :param filename: name of previously uploaded file
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/schemas/v1/document/report_type.json
> +    "report_type": {
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/schemas/v1/document/subjects.json
> +    "subjects": {
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on app/schemas/v1/document/submission.json
> +                "maxLength": "Please shorten your description to at most 200 characters.",
@gzhou1 any update on this?

2017-06-21 13:23 UTC, joelbcastillo commented on gpp/src/components/DateInput.js
> +    // update the date value if the format is valid, even though the date itself might be wrong
:+1:

2017-06-21 13:23 UTC, joelbcastillo commented on gpp/src/components/FileUpload.js
> +      errorMsg = "Failed to upload file due to an unhandled server error."
@gzhou1 Any update on this?

2017-06-21 13:25 UTC, joelbcastillo approved these changes

2017-06-21 13:25 UTC, merged